name: CI

on:
  pull_request:
  push:

env:
  BIG_QUERY_PROJECT: ${{ secrets.BIGQUERY_PROJECT }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - name: Build and Test
        uses: actions-hub/gcloud@master
          env:
            PROJECT_ID: ${{ secrets.BIGQUERY_PROJECT }}
            APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_64 }}
        run: sbt -v -Dfile.encoding=UTF-8 +test
