name: CI

on:
  pull_request:
  push:

env:
  BIG_QUERY_PROJECT: ${{ secrets.BIGQUERY_PROJECT }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Use gcloud CLI
        run: gcloud info
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - name: Set up GCloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.BIGQUERY_PROJECT }}
          service_account_key: ${{ secrets.BQ_SERVICE_ACCOUNT_64 }}
          export_default_credentials: true
      - name: Build and Test
        run: sbt -v -Dfile.encoding=UTF-8 +test
