name: release
on:
  push:
    # branches: [master]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v10
      - uses: olafurpg/setup-gpg@v2
      - name: Publish
        run: |
          git ls-remote --get-url origin
          csbt ci-release
        env:
          PGP_PASSPHRASE:
          PGP_SECRET: ${{ secrets.GPG_KEY }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
